#rexrov/thruster_allocator:
/**:
  ros__parameters:
    thruster_manager:
      tf_prefix: rexrov
      base_link: base_link
      thruster_topic_prefix: thrusters/
      thruster_topic_suffix: /input
      thruster_frame_base: thruster_
      max_thrust: 2000.0
      timeout: -1.0
      update_rate: 50.0
      conversion_fcn: proportional
      conversion_fcn_params:
        gain: 0.00031
