# generated from rosidl_cmake/cmake/rosidl_cmake-extras.cmake.in

set(uuv_thruster_manager_IDL_FILES "srv/GetThrusterCurve.idl;srv/ThrusterManagerInfo.idl;srv/SetThrusterManagerConfig.idl;srv/GetThrusterManagerConfig.idl")
set(uuv_thruster_manager_INTERFACE_FILES "srv/GetThrusterCurve.srv;srv/GetThrusterCurve_Request.msg;srv/GetThrusterCurve_Response.msg;srv/ThrusterManagerInfo.srv;srv/ThrusterManagerInfo_Request.msg;srv/ThrusterManagerInfo_Response.msg;srv/SetThrusterManagerConfig.srv;srv/SetThrusterManagerConfig_Request.msg;srv/SetThrusterManagerConfig_Response.msg;srv/GetThrusterManagerConfig.srv;srv/GetThrusterManagerConfig_Request.msg;srv/GetThrusterManagerConfig_Response.msg")
