
publish_world_models:
    ros__parameters:
      meshes:
        seabed:
          mesh: package://uuv_gazebo_worlds/models/munkholmen_seabed/meshes/seabed.dae
            pose:
              position: [0., 0., 0.]
        island:
          mesh: package://uuv_gazebo_worlds/models/munkholmen/meshes/munkholmen.dae
            pose:
              position: [-103.391, -121.403, 0.]
        herkules_ship_wreck:
            mesh: package://uuv_gazebo_worlds/models/herkules_ship_wreck/meshes/herkules.dae
            pose:
              position: [1052.025, 158.035, -50.]
              orientation: [0., 0., 5.24]