/**:
  ros__parameters:
    disturbances:
      d1:
        type: current
        starting_time: 5.0
        velocity: 2.0
        horizontal_angle: 2.5
        vertical_angle: 1.5
        duration: 4.0
      d2:
        type: wrench
        starting_time: 8.0
        duration: 2.0
        force: [0.0, 0.0, 0.0]
        torque: [0.0, 0.0, 0.0]
      d3:
        type: thruster_state
        starting_time: 14.0
        duration: 20.0
        thruster_id: 0
        is_on: false
      d4:
        type: propeller_efficiency
        starting_time: 18.0
        duration: 5
        thruster_id: 1
        efficiency: 0.4
      d5:
        type: thrust_efficiency
        starting_time: 20.0
        duration: 10.0
        thruster_id: 5
        efficiency: 0.0


# /**:
#     ros__parameters:
#       disturbances:
#         -
#           type: current
#           starting_time: 5.0
#           velocity: 2.0
#           horizontal_angle: 2.5
#           vertical_angle: 1.5
#           duration: 4.0
#         -
#           type: wrench
#           starting_time: 8.0
#           duration: 2.0
#           force: [0.0, 0.0, 0.0]
#           torque: [0.0, 0.0, 0.0]